### ISSUE TITLE
Patterns in Python

### ISSUE THREAD

**Issue by anushkasaxena27** [ratnesh-maurya/HACTOBERFEST_2022#145]
I would like to add code for all important patterns in python

**Comment by aditi072** [comment]
I will like to contribute all the major patterns in C++ . Floyd's Triangle , butterfly, pyramids etc.
Please assign me the issue & add Hactoberfest tag.

Thankyou!

**Comment by anushkasaxena27** [comment]
I have added all important python programs in a single file
