### ISSUE TITLE
Linked List in C++

### ISSUE THREAD

**Issue by BTANISHA11** [ratnesh-maurya/HACTOBERFEST_2022#237]
I want to add program to insert a node at beginning and end in linked list in C++.
can you pls assign this to me @ratnesh-maurya

**Comment by kiranmayek** [comment]
I want to implement polynomial addition and multiplication using linked list . Can you please assign this 
And if possible could you please add hacktoberfest tag

**Comment by RishabhSharma96** [comment]
@ratnesh-maurya please assign.

**Comment by BTANISHA11** [comment]
Added Linked list in C++ @ratnesh-maurya

**Comment by BTANISHA11** [comment]
Pls add hacktober fest label to it
its showing excluded
@ratnesh-maurya
