### ISSUE TITLE
Nth room of a number using Binary Search

### ISSUE THREAD

**Issue by GarimaMahajan20** [ratnesh-maurya/HACTOBERFEST_2022#321]
Given a number m find its nth root using Binary Search

**Comment by GarimaMahajan20** [comment]
Hey @ratnesh-maurya, Can u add Hacktoberfest label to this?

**Comment by am-my11** [comment]
@ratnesh-maurya  I have added the code for this, can u assign this to me. 
https://github.com/ratnesh-maurya/HACTOBERFEST_2022/pull/312
